### ISSUE TITLE
Do you plan to support Chinese clients?

### ISSUE THREAD

**Issue by soalu** [Slazanger/SMT#103] opened 2023-01-20 07:10 UTC
Do you plan to support Chinese clients?

**Comment by Slazanger** [comment] 2023-01-23 12:18
I am going to add localisation support for the UI;  the game side is a little more complicated as I need to know the log keywords for certain things

**Comment by goblock2021** [comment] 2023-01-24 10:12
@Slazanger If you need the Chinese translation, I may help you.

**Comment by Slazanger** [comment] 2023-09-05 16:30
duplicate of  https://github.com/Slazanger/SMT/issues/106

**Closed by Slazanger** 2023-09-05 16:30 UTC

**Comment by Binkcn** [comment] 2024-06-27 10:03
I am already starting to do this, although I am not very good at writing C #, the good news is that XAML syntax makes it easy to handle support for multiple languages.
